from pathlib import Path

from core.artifacts import load_json


def _field(finding: dict, *names: str, default: str = "") -> str:
    for name in names:
        value = finding.get(name)
        if value:
            return value
    return default


def _build_final_summary(base_dir: Path, target: str) -> None:
    surfaces = load_json(base_dir / "surfaces" / "attack_surfaces.json", [])
    tasks = load_json(base_dir / "tasks" / "validation_tasks.json", [])
    candidates = load_json(base_dir / "findings" / "candidates.json", [])
    reportable = load_json(base_dir / "findings" / "reportable.json", [])
    discarded = load_json(base_dir / "surfaces" / "discarded_items.json", [])
    method_coverage = load_json(base_dir / "recon" / "subdomain_method_coverage.json", [])
    subdomain_status = load_json(base_dir / "recon" / "subdomain_master_status.json", {})
    missing_tools_path = base_dir / "recon" / "missing_tools.txt"
    missing_tools = []
    if missing_tools_path.exists():
        missing_tools = [line.strip() for line in missing_tools_path.read_text(encoding="utf-8", errors="ignore").splitlines() if line.strip()]
    coverage_lines = []
    for item in method_coverage[:30]:
        coverage_lines.append(f"- `{item.get('method', 'unknown')}`: {item.get('status', 'unknown')} ({item.get('note', '')})")
    if len(method_coverage) > 30:
        coverage_lines.append(f"- ... {len(method_coverage) - 30} more methods")
    missing_lines = [f"- `{tool}`" for tool in missing_tools[:50]]
    if len(missing_tools) > 50:
        missing_lines.append(f"- ... {len(missing_tools) - 50} more tools")
    summary = f"""# Final Summary: {target}

## Artifact Counts
- Attack surfaces: {len(surfaces)}
- Validation tasks: {len(tasks)}
- Candidate findings: {len(candidates)}
- Reportable findings: {len(reportable)}
- Discarded/skipped items: {len(discarded)}
- Subdomain method coverage entries: {len(method_coverage)}
- Missing subdomain tools: {len(missing_tools)}

## Subdomain Automation
- Complete: {subdomain_status.get('complete', False)}
- Output folder: `{subdomain_status.get('subdomain_dir', '')}`
- Coverage file required: `recon/subdomains/method_coverage.jsonl`

## Method Coverage
{chr(10).join(coverage_lines) if coverage_lines else "- No method coverage loaded."}

## Missing Tools
{chr(10).join(missing_lines) if missing_lines else "- None recorded."}

## Report Gate
Findings are reportable only when reproducible request, curl, response proof, impact, false-positive checks, manual validation, and severity mapping are present.

## Required Artifacts
- `recon/subdomains.txt`
- `recon/resolved.txt`
- `httpx/httpx_full.jsonl`
- `httpx/httpx_alive.txt`
- `urls/collected_urls.txt`
- `urls/params.txt`
- `js/js_files.txt`
- `js/endpoints.txt`
- `js/secrets_candidates.json`
- `surfaces/attack_surfaces.json`
- `tasks/validation_tasks.json`
- `findings/candidates.json`
- `findings/reportable.json`
"""
    (base_dir / "reports").mkdir(parents=True, exist_ok=True)
    with open(base_dir / "reports" / "final_summary.md", "w", encoding="utf-8") as handle:
        handle.write(summary)


def build_report(finding: dict, base_dir: Path):
    report_dir = base_dir / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    if finding.get("summary_only"):
        _build_final_summary(base_dir, finding.get("target", "unknown"))
        return

    finding_id = finding.get("id", "finding")
    print(f"[*] Building Report for {finding_id}")
    report_file = report_dir / f"REPORT_{finding_id}.md"
    finding_type = _field(finding, "finding_type", "vulnerability_class", default="Finding")
    curl = _field(finding, "curl", "curl_poc")
    severity = _field(finding, "severity", "severity_guess", default="Unmapped")
    vrt = finding.get("bugcrowd_vrt", {})

    markdown = f"""# Title: {finding_type} on {_field(finding, 'asset')}

## Summary
A manually validated `{finding_type}` candidate affects `{_field(finding, 'endpoint')}`.

## Asset
- **Target:** {_field(finding, 'target')}
- **Endpoint:** {_field(finding, 'endpoint')}

## VRT Mapping
- **Category:** {vrt.get('category')}
- **Subcategory:** {vrt.get('subcategory')}
- **Priority:** {vrt.get('priority')}

## Severity
**{severity}**

## Steps to Reproduce
"""
    for step in finding.get("manual_validation_steps") or finding.get("reproduction_steps", []):
        markdown += f"- {step}\n"

    markdown += f"""
## PoC
```bash
{curl}
```

## Evidence
**Request:**
```http
{finding.get('request', '')}
```

**Response:**
```http
{finding.get('response', '')}
```

**Proof:**
{finding.get('proof', '')}

## Impact
{finding.get('impact', '')}

## False Positive Checks
"""
    for check in finding.get("false_positive_checks", []):
        markdown += f"- [x] {check}\n"

    markdown += "\n## Notes\nGenerated by reco from report-gated evidence.\n"
    with open(report_file, "w", encoding="utf-8") as handle:
        handle.write(markdown)
    print(f"[+] Report generated: {report_file}")
